export default {
  AUTH_MISSING: 'AUTH_MISSING',
  AUTH_HEADER_INVALID: 'AUTH_HEADER_INVALID',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_DISABLED: 'USER_DISABLED',
  BAD_REQUEST: 'BAD_REQUEST',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
